### ISSUE TITLE
Unexpected symbol: '^' (0x5e)

### ISSUE THREAD

**Issue by a-hansen** [skyfoundry/haystack-java#6]
The following is happening in version 3.0.5, against SkySpark 3.0.26.  My customer is reporting that one of the tags equals or contains the '^' char.  Is this a problem with this lib, or some sort of version incompatibility?

[2020-11-20 15:01:47.452115] 2020-11-20 15:01:47.451 [Thread-4] ERROR org.dsa.iot.haystack.Haystack - read(navName == "SaTemp")
[2020-11-20 15:01:47.452115] org.projecthaystack.ParseException: Unexpected symbol: '^' (0x5e) [line 3]
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.io.HaystackTokenizer.err(HaystackTokenizer.java:469)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.io.HaystackTokenizer.symbol(HaystackTokenizer.java:430)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.io.HaystackTokenizer.next(HaystackTokenizer.java:89)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.io.HZincReader.consume(HZincReader.java:385)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.io.HZincReader.consume(HZincReader.java:376)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.io.HZincReader.parseLiteral(HZincReader.java:218)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.io.HZincReader.parseVal(HZincReader.java:157)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.io.HZincReader.parseGrid(HZincReader.java:313)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.io.HZincReader.readVal(HZincReader.java:76)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.io.HZincReader.readGrid(HZincReader.java:92)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.client.HClient.postGrid(HClient.java:606)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.client.HClient.call(HClient.java:597)
[2020-11-20 15:01:47.452115] 	at org.projecthaystack.client.HClient.eval(HClient.java:253)
[2020-11-20 15:01:47.452115] 	at org.dsa.iot.haystack.Haystack$5.handle(Haystack.java:160)
[2020-11-20 15:01:47.452115] 	at org.dsa.iot.haystack.Haystack$5.handle(Haystack.java:156)
[2020-11-20 15:01:47.452115] 	at org.dsa.iot.haystack.helpers.ConnectionHelper.connect(ConnectionHelper.java:164)
[2020-11-20 15:01:47.452115] 	at org.dsa.iot.haystack.helpers.ConnectionHelper.getClient(ConnectionHelper.java:133)
[2020-11-20 15:01:47.452115] 	at org.dsa.iot.haystack.Haystack.eval(Haystack.java:156)
[2020-11-20 15:01:47.452115] 	at org.dsa.iot.haystack.actions.Actions$4.handle(Actions.java:290)
[2020-11-20 15:01:47.452115] 	at org.dsa.iot.haystack.actions.Actions$4.handle(Actions.java:284)
[2020-11-20 15:01:47.452115] 	at org.dsa.iot.dslink.node.actions.Action.invoke(Action.java:159)

Thanks,
Aaron

**Comment by mgiannini** [comment]
We need to add [Symbol kind](https://project-haystack.dev/doc/docHaystack/Kinds#symbol) support to the library. The `^` is used to encode a `^symbol`

**Comment by a-hansen** [comment]
Thanks Matthew, have a great weekend.

**Comment by mgiannini** [comment]
Commit bef09e6 fixes issue #6

**Comment by mgiannini** [comment]
FYI - `org.projecthaystack:haystack-java:3.0.6` has this fix in it on bintray/jcenter
